### ISSUE TITLE
JAVA Out of of Memory

### ISSUE THREAD

**Issue by Maux82** [BimberLab/DISCVRSeq#227]
Hi,

I am running VariantQC using docker (tag latest) with  multiple Input VCFs (-V sampleName sampleName.vcf.gz ) option.  I have more than 1500 samples that I would like to have in the same report, but  when I run it I get an error out of memory. 
I have tried to specify the memory size in docker command but did not help. Moreover, I have increased the java heap memory size (-Xms ) but does not works as a input option.

Do you know a way to increase the  memory   ? 
Have you tried to run it with the multiple Input VCFs on so many samples ?

**Comment by bbimber** [comment]
Hi @Maux82, for one of my lab's projects (https://mgap.ohsu.edu/) we run this on about 3000. But yes, once you get that large this can be an issue. We run those jobs on a cluster and generally would give java -Xmx of 172 or so. What were you actually using?

In our hands, we generally don't get memory errors, but VCFs with lots of samples can take an extremely long time. You can split by chromosome, but this results in some loss of information since you need to re-aggregate and the HTML loses some of the benefits (though has some use). I might consider taking your VCF and subsetting into three VCFs with 500 samples/ea and running. Most of the memory requirement is coming from loading and passing around that many genotypes. VariantQC essentially works by running multiple instances of VariantEval.
