### ISSUE TITLE
No 'Intersection' set produced by MergeVcfsAndGenotypes

### ISSUE THREAD

**Issue by pruzanov** [BimberLab/DISCVRSeq#228]
I tried this tool with multiple vcfs using PRIORITIZE option. With GATK it used to produce 'set' values indicating whether it passed in one caller/filtered in another caller and 'Intersection'. However, I see that DISCVRSeq **MergeVcfsAndGenotypes** generates only entries where 'set' shows only ROD names. The provided documentation does not indicate that any special option needs to be used to enable the desired behavior, though it mentions 'Intersection' tag. Is it possible that this feature is not fully implemented?

**Comment by bbimber** [comment]
It seems that this is an error in the docs. This took relies very heavily on GATK's code. In the GATK CombineVariants tool, this feature was provided by GATKVariantContextUtils: https://github.com/broadgsa/gatk/blob/41147a655594c2aae6e2cad8462bd1648570b32b/public/gatk-utils/src/main/java/org/broadinstitute/gatk/utils/variant/GATKVariantContextUtils.java#L1323. And in GATK4 it seems like this part of the code path no long is included. 

I think since 'set' is added to the output, you could run a second SelectVariants command to do the filtering. I updated the docs in DISCVRseq to reflect that.
